### ISSUE TITLE
Generate core/v1 controller in shepherd to resolve missing resources

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/shepherd#166]
It appears that the core/v1 controller being used is outdated, resulting in the absence of resources such as limitranges. @igomez06 suggested that the core/v1 controller needs to be generated in shepherd to ensure it reflects the latest API changes.

**Comment by floatingman** [comment]
@Priyashetty17 We will probably pick this up in the next sprint that is starting next week.

**Comment by floatingman** [comment]
@Priyashetty17 I've reviewed this, and it looks like the controllers for core/v1 come directly from the Wrangler project and are not part of the Rancher-generated controllers. So, any functionality using Wrangler with the test framework should match what Rancher uses.

Here is where the controllers are. https://github.com/rancher/wrangler/tree/master/pkg/generated/controllers/core
and we have the same version of Wrangler that is used in Rancher

**Comment by Priyashetty17** [comment]
@floatingman Thanks for looking into this! Sice limitranges is not availabe in this version, do you suggest we use dynamic client for limitranges? cc @igomez06

**Comment by igomez06** [comment]
> @Priyashetty17 I've reviewed this, and it looks like the controllers for core/v1 come directly from the Wrangler project and are not part of the Rancher-generated controllers. So, any functionality using Wrangler with the test framework should match what Rancher uses.
> 
> Here is where the controllers are. https://github.com/rancher/wrangler/tree/master/pkg/generated/controllers/core and we have the same version of Wrangler that is used in Rancher

HI @floatingman and @Priyashetty17, the limit ranges is a new feature on k8s right? Or is this something added from Rancher? Dan my thinking is we generate the core controllers in shepherd, because we need the session clean up added to it anyways. We wouldn't want to import it from the wrangler repo.

**Comment by Priyashetty17** [comment]
@igomez06 Limitranges is a k8s feature - https://kubernetes.io/docs/concepts/policy/limit-range/

**Comment by floatingman** [comment]
https://github.com/rancher/shepherd/pull/207
https://github.com/rancher/shepherd/pull/208
