### ISSUE TITLE
Jobs in Actions triggered from PRs did not terminate according to the Job, but the Action is marked as ✅ 

### ISSUE THREAD

**Issue by slickwarren** [rancher/shepherd#192]
2 of the jobs in some recent actions didn't terminate correctly for some reason. Not sure if there's a way to kill it, or if this is a reporting issue on GH end. Any idea why this would happen? 
https://github.com/rancher/shepherd/actions/runs/9068853771 
https://github.com/rancher/shepherd/actions/runs/9068853253 
 It doesn't appear to be accruing any usage from this, but we had to push a small change to the PR in order to get a :white_check_mark: which just created a new action, where the job and action successfully passed

**Comment by sowmyav27** [comment]
Actions had a problem yesterday - https://www.githubstatus.com/history

```
[Incident with Actions]
This incident has been resolved.
May 13, 19:51 - 20:10 UTC
```

**Comment by caliskanugur** [comment]
Update: Seems like both of the jobs are still running

**Comment by rancher-max** [comment]
Seems like this is a UI issue. If so, we'll just close this out.

**Comment by caliskanugur** [comment]
Both runs' first attempts seem cleaned up, including their run time and logs. 

To ensure the runs are completed at the backend side; force-cancel requests have been used as confirmations.(`https://api.github.com/repos/rancher/shepherd/actions/runs/<runID>/force-cancel`)

Both requests responded with:

```
{
  "message": "Cannot cancel a workflow run that is completed.",
  "documentation_url": "https://docs.github.com/rest/actions/workflow-runs#force-cancel-a-workflow-run",
  "status": "409"
}
```
